//
// NOTE: THIS FILE IS AUTO-GENERATED by the "TdApiKtxGenerator".kt
// See: https://github.com/tdlibx/td-ktx-generator/
//
package com.xbot.tdlibx.coroutines

import com.xbot.tdlibx.core.TelegramFlow
import kotlin.Boolean
import kotlin.String
import org.drinkless.tdlib.TdApi
import org.drinkless.tdlib.TdApi.FormattedText
import org.drinkless.tdlib.TdApi.WebPage
import org.drinkless.tdlib.TdApi.WebPageInstantView

/**
 * Suspend function, which returns an instant view version of a web page if available. Returns a 404
 * error if the web page has no instant view page.
 *
 * @param url The web page URL.  
 * @param forceFull Pass true to get full instant view for the web page.
 *
 * @return [WebPageInstantView] Describes an instant view page for a web page.
 */
suspend fun TelegramFlow.getWebPageInstantView(url: String?, forceFull: Boolean): WebPageInstantView
    = this.sendFunctionAsync(TdApi.GetWebPageInstantView(url, forceFull))

/**
 * Suspend function, which returns a web page preview by the text of the message. Do not call this
 * function too often. Returns a 404 error if the web page has no preview.
 *
 * @param text Message text with formatting.
 *
 * @return [WebPage] Describes a web page preview.
 */
suspend fun TelegramFlow.getWebPagePreview(text: FormattedText?): WebPage =
    this.sendFunctionAsync(TdApi.GetWebPagePreview(text))
